config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'rewards#index'

  resource :session, only: [:new, :create, :destroy]
  resource :setting, only: [:edit, :update]
  resources :rewards, only: [:index]

  scope '/api/v1', defaults: { format: 'json' } do
    resource :session, only: [:create, :destroy]
    resource :setting, only: [:show, :update]
    resources :rewards, only: [:index]
  end
end

app/models/account.rb
class Account < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  has_secure_password

  has_many :sessions
  has_many :rewards

  validates_presence_of :email, uniq: true
  validates_format_of :email, with: VALID_EMAIL_REGEX
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perk.rb
class Perk < ActiveRecord::Base
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :account

  enum status: {
    waiting_to_be_approved: 0,
    approved: 1,
    denied: 2,
    sent: 3,
    redeemed: 4,
    completed: 5
  }

  scope :by_status, -> (status) { status.blank? ? all : where(status: status) }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :account

  validates_presence_of :account_id, :token
  validates_uniqueness_of :token

  before_validation :generate_token, on: :create

  private

  def generate_token
    self.token = SecureRandom.hex(16)
  end
end

app/controllers/Api/V1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, :if => Proc.new { |c| c.request.format == 'application/vnd.datatestapp.v1' }
  before_filter :load_json
  respond_to :json

  rescue_from Exception, with: :generic_exception
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  private
  def record_not_found(error)
    respond_to do |format|
      format.json { render :json => {:error => error.message}, :status => 404 }
    end
  end

  def generic_exception(error)
    respond_to do |format|
      format.json { render :json => {:error => error.message}, :status => 500 }
    end
  end

  # reading and parsing data into an array of has
  def load_json
    test_data = JSON.parse(File.read(File.join(Rails.root, 'public', 'data.json')), quirks_mode: true)
    Perk.destroy_all

    test_data.each do |item|
      Perk.create({
        id: item["id"].to_i,
        user_id: item["user_id"].to_i,
        experience: item["experience"],
        date: item["date"],
        status: item["status"]
      })
    end
  end
end

app/controllers/Api/V1/data_controller.rb
class Api::V1::DataController < Api::V1::BaseController
  before_filter :load_data
  before_filter :find_item, only: [:show, :update, :destroy]

  def index
    items_per_page = 5

    render json: @data
  end

  def destroy
    if @item.destroy
      write_to_json
      render json: @data
    else
      render json: {message: "something went wrong, wasn't able to delete item"}
    end
  end

  def update
    if @item
      @item.update_attributes(item_params)
      write_to_json
      render json: @data
    else
      render json: {message: "item not found."}
    end
  end

  def show
    if @item
      render json: @item
    else
      render json: {message: "item not found."}
    end
  end

  def create
    if params["user"] and params["experience"]
      @item = Perk.create({
        user_id: params["user"],
        experience: params["experience"],
        date: Date.today,
        status: "New"
      })
      write_to_json
      render json: @data
    else
      render json: {message: "user and experience is required"}
    end
  end

  private
  #load all data from database
  def load_data
    @data = Perk.all
  end

  #find item for delete, update, and show with before_filter
  def find_item
    @item = Perk.find(params["id"].to_i)
  end

  #strong parameters for security
  def item_params
    params.permit(:id, :user, :experience, :status)
  end

  def filter_params
    params.permit(:page, :filter, :query)
  end

  #write data to json every operation
  def write_to_json
    File.open(File.join(Rails.root, 'public', 'data.json'), 'w') do |file|
      file.write(@data.to_json)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  before_action :authorize!

  helper_method :current_account

  private

  def authorize!
    return true if current_account
    respond_to do |format|
      format.json { head :unauthorized }
      format.html { redirect_to new_session_path }
    end
  end

  def current_account
    @account ||= Session.find_by(token: session_token)&.account
  end

  def session_token
    session[:token] || request.headers['Authorization']&.split(' ')&.last
  end
end

app/controllers/concerns/api_constraints.rb
class ApiConstraints
  def initialize(options)
    @version = options[:version]
    @default = options[:default]
  end

  def matches?(req)
    @default || req.headers['Accept'].include?("application/vnd.datatestapp.v#{@version}")
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = current_account.rewards.by_status(params[:status]).page(params[:page])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize!, only: [:new, :create]

  def new
  end

  def create
    account = Account.find_by(email: params[:email])&.authenticate(params[:password])
    account ? set_up_session(account) : failed_authentication
  end

  def destroy
    Session.find_by(token: session_token).destroy
    session.delete('token')
    respond_to do |format|
      format.json { head :ok }
      format.html { redirect_to new_session_path }
    end
  end

  def set_up_session(account)
    account_session = account.sessions.create
    respond_to do |format|
      format.json do
        response.headers['Authorization'] = "Base #{account_session.token}"
        head :ok
      end

      format.html do
        session[:token] = account_session.token
        redirect_to root_path
      end
    end
  end

  def failed_authentication
    respond_to do |format|
      format.json { render status: :unprocessable_entity, json: { errors: ['Email or password is wrong'] } }
      format.html { redirect_to new_session_path, alert: 'Email or password is wrong' }
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def show
    render json: current_account
  end

  def edit
  end

  def update
   if current_account.update(update_params)
     respond_to do |format|
       format.json { render json: current_account }
       format.html { redirect_to edit_setting_path, notice: 'Updated' }
     end
   else
     errors = current_account.errors.to_a
     respond_to do |format|
       format.json { render json: { errors: errors } }
       format.html { render :edit, alert: errors.join(', ') }
     end
   end
  end

  private

  def update_params
    params.require(:account).permit(:password, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendEngineerApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <table style="width: 100%">
      <tr>
        <td style="width: 15%; vertical-align: top;" >
          Menu
          <br>
          <ul>
            <% if current_account %>
                <li>
                  <%= link_to 'Rewards', rewards_path %>
                </li>
                <li>
                  <%= link_to 'Settings', edit_setting_path %>
                </li>
                <li>
                  <%= link_to 'Sign out', session_path, method: :delete %>
                </li>
            <% else %>
                <li>
                  <%= link_to 'Sign in', new_session_path %>
                </li>
            <% end %>
          </ul>
        </td>

        <td style="width: 85%" >
          <% if flash[:alert] %>
              <div style="width: 100%; border: 1px solid red">
                <%= flash[:alert] %>
              </div>
          <% end %>

          <% if flash[:notice] %>
              <div style="width: 100%; border: 1px solid green">
                <%= flash[:notice] %>
              </div>
          <% end %>

          <%= yield %>
        </td>
      </tr>
    </table>
  </body>
</html>

app/views/rewards/index.html.erb
<%= form_tag '/rewards', method: :get do %>
  Filter by status
  <%= select_tag :status,
                 options_for_select(Reward.statuses.to_a, params[:status]),
                 include_blank: true,
                 onchange: 'this.form.submit()' %>
<% end %>

<table>
  <tr>
    <th>#</th>
    <th>Status</th>
  </tr>

  <% @rewards.each do |reward| %>
    <tr>
      <td><%= reward.id %></td>
      <td><%= reward.status %></td>
    </tr>
  <% end %>
</table>

<%= paginate @rewards %>

app/views/settings/edit.html.erb
<%= form_for current_account, url: setting_path do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :email %><br>
    <%= f.text_field :email %><br>

    <%= f.label :password %><br>
    <%= f.text_field :password, placeholder: 'Leave blank if you do not want to change the password' %><br>

    <%= f.submit %>
<% end %>